name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - 'live/**'
      - 'modules/**'

permissions:
  id-token: write
  contents: read

concurrency:
  group: tf-apply
  cancel-in-progress: false

jobs:
  apply:
    name: Terragrunt Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1
          role-session-name: GitHubActions-Apply

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.77.0/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Terragrunt Apply
        working-directory: live/eu-west-1/dev
        run: terragrunt run-all apply --terragrunt-non-interactive --auto-approve
